---
title: "Project Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Final Report

## Motivation

With air quality becoming a great concern of modern era, especially as an important public health topic. Environmental health is an important factor of our health as well. Air pollution has always been a big concern in public health topic. Since we believe it is a common cause such as Asthma, cardiovascular diseases, and many other health problems. So we decided to propose some analytical tests on correlation between these factors and air pollution. 

We are curious on investigating on the effects of several potential factors and their relationship to AQI(air quality index), an indicating value of air quality. We are interested in air quality problems within NY state and at each county level from year 2003 to 2012. We aim to figure out the main causes of poor air quality and help health organizations and the public better assess and deal with the problem.


## Questions and Planned Analysis

**Questions:**

1. What are rates of Asthma in each county in NY state across years?
2. What are rates of heart diseases in each county in NY state across years?
3. What pollutants distributions in each county in NY state across years?
4. What are the AQI conditions in each county in NY state aross years?

**Planned Analysis**

1. Asthma and AQI
2. Heart diseases and AQI
3. Pollutants and AQI


## Data Processing and Cleaning

We referred to two data sources to construct our main dataset for further analysis. The air quality information (including daily aqi and six pollutant parameters) are from EPA database, and those health related data are from CDC Behavioral Risk Factor Surveillance System (BRFSS).

a. Daily aqi for each county in New York State from 2003 to 2012 [(dataset)](https://aqs.epa.gov/aqsweb/airdata/download_files.html#AQI)

We downloaded daily aqi files from “Daily AQI by County” Section ranged from 2003 to 2012 (one .csv file per year). Each dataset contains daily air quality index and other relative information for each county in the United States over a whole year. Those raw data files are stored in the “daily_aqi” folder from the “data” subdirectory in our repository. 

For the process of data cleaning, firstly we used map function to combine those 10 datasets in order by year. Then we filtered by state name to keep counties that belong to New York State. Finally, we kept these variables that we will focus on:

* state: state name, New York State specifically
* county: county names in New York State
* date: date on which the air quality was monitored
* aqi: air quality index value
* category: levels of health concern according to aqi
* defining_parameter: pollutants that define the aqi on that day
* defining_site: the site code that define the daily aqi on that day (consists of state code, county code, and site code, separated by “-”)

The resulting dataset was saved as an object named “full_aqi” in data_import_cleaning.Rmd file.

b. Six main parameter values [(dataset)](https://aqs.epa.gov/aqsweb/airdata/download_files.html#Daily)

According to the National Weather Service, EPA calculates the AQI for five major air pollutants regulated by the Clean Air Act: ground-level ozone, particle pollution (also known as particulate matter), carbon monoxide, sulfur dioxide, and nitrogen dioxide. In the EPA database, each daily summary file contains data for every monitor (sampled parameter) for each day. These files are separated by parameter (or parameter group) to make the sizes more manageable. As a result, we collected 60 data files concerning daily values about six pollutants (carbon monoxide, sulfur dioxide, nitrogen dioxide, ozone, PM2.5, and PM10) in each county from 2003 to 2012 (one .csv file per year per parameter). Those data files are stored in the “daily_parameter” folder from the “data” subdirectory in our repository. What should be pointed out is that files from ozone, pm2.5, and so2 categories were pre-processed (filter by state name “New York”) in pre-processing.Rmd file, since the size of most of them exceeded the 100M git push limit. After the pre-processing, files in `ozone`, `pm2.5`, and `so2` folder contain data for New York State, others contain data across the US.

During the process of data cleaning, we first combined 10-year datasets for each parameter using map function, then filtered by “New York'' state name, and selected the main variables that we were concerned about. Six data frames were created after these. Secondly, for each dataframe, we extracted daily parameter mean values from different sites for each county using “group_by” and “summarize” statements. Six summary tables were produced. 

Main variables in the six daily parameter tables we focus on:

* county: county names in New York State
* date: date on which the air quality was monitored
* mean_ozone: the average ozone value for the day within that county (unit of measure: parts per million)
* max_ozone: the highest ozone value for the day within that county (unit of measure: parts per million)
* mean_co: the average carbon monoxide value for the day within that county (unit of measure: parts per million)
* max_co: the highest carbon monoxide value for the day within that county (unit of measure: parts per million)
* mean_no2: the average nitrogen dioxide value for the day within that county (unit of measure: parts per million)
* max_no2: the highest nitrogen dioxide value for the day within that county (unit of measure: parts per million)
* mean_so2: the average sulfur dioxide value for the day within that county (unit of measure: parts per million)
* max_so2: the highest sulfur dioxide value for the day within that county (unit of measure: parts per million)
* mean_pm2_5: the average pm2.5 value for the day within that county (unit of measure: Micrograms/cubic meter (LC))
* max_pm2_5: the highest pm2.5 value for the day within that county (unit of measure: Micrograms/cubic meter (LC))
* mean_pm10: the average pm10 value for the day within that county (unit of measure: Micrograms/cubic meter (25 C))
* max_pm10: the highest pm10 value for the day within that county (unit of measure: Micrograms/cubic meter (25 C))

The “full_aqi” table from part a and daily parameter tables were left-joined using columns “county” and “date” (full_aqi as left table). In addition, the “defining_site” variable was separated as state_code, county_code, and site_code. The state_code and county_code were kept in the resulting dataset “air_daily”. The air_daily dataset was also saved as air_daily.csv file in the “data” folder.

c. Individual health survey data in New York State from 2003 to 2012

The annual survey data from CDC Behavioral Risk Factor Surveillance System provides information on the background, design, data collection and processing, statistical, and analytical issues. It also provides health related information of each interviewee. We gathered 10 raw data files (1 file per year) for processing.

Firstly, we filtered by state code 36, then selected variables we were interested in. Finally, we filtered out rows in which county code was missing.

Main variables:
* state_code: state FIPS Codes, New York State code 36 specifically
* county_code: county FIPS Codes in New York State
* year: interview year
* month: interview month
* day: interview day
* asthma: ever told had asthma; 1 for yes, 0 for no
* asthma_now: still have asthma; 1 for yes, 0 for no
* asthma_age: age at asthma diagnosis
* asthma_attack: asthma during past 12 months; 1 for yes, 0 for no
* asthma_emergency: how many times of visiting an emergency room or urgent care center because of asthma during past 12 months
* asthma_visit: how many times of urgent asthma treatment during past 12 months
* asthma_symptom: frequencies of asthma symptoms during past 30 days; 0 for none, 1 for less than once a week, 2 for once or twice a week, 3 for more than 2 times a week but not every day, 4 for every day but not all the time, 5 for every day all the time
* asthma_status: computed asthma status, 1 for current, 2 for former, 3 for never
* asthma_history: risk factor for lifetime asthma prevalence, 1 for not at risk, 2 for at risk
* asthma_current: risk factor for current asthma prevalence, 1 for not at risk, 2 for at risk
* physical_health: number of days physical health not good during the past 30 days
* mental_health: number of days mental health not good during the past 30 days
* coronary_heart_disease: angina or coronary heart disease, 1 for yes, 0 for no
* heart_attack: ever diagnosed with heart attack, 1 for yes, 0 for no
* stroke: ever diagnosed with stroke, 1 for yes, 0 for no
* education: level of education completed, 1 for did not graduate high school, 2 for graduated high school, 3 for attended college or technical school, 4 for graduated from college or technical school
* sex: respondents sex, 1 for male, 2 for female
* smoker: computed smoking status, 1 for current smoker - now smokes every day, 2 for current smoker - now smokes some days, 3 for former smoker, 4 for never smoked
* race: race categories, 1 for White only, non-hispanic, 2 for Black only, non-hidpanic, 3 for Asian only, non-hispanic, 4 for Native Hawaiian or other Pacific Islander only, non-hispanic, 5 for American Indian or Alaskan Native only, non-hispanic, 6 for other race only, non-hispanic, 7 for multiracial, non-hispanic, 8 for hispanic
* age: reported age in five-year age categories, 1 for age 18-24, 2 for 25-29, 3 for 30-34, 4 for 35-39, 5 for 40-44, 6 for 45-49, 7 for 50-54, 8 for 55-59, 9 for 60-64, 10 for 65-69, 11 for 70-74, 12 for 75-79, 13 for 80 or older
* income: income categories, 1 for less than $15000, 2 for $15000 to less than $25000, 3 for $25000 to less than $35000, 4 for $35000 to less than $50000, 5 for $50000 or more

The combined 10-year brfss files was saved as a dataframe named “brfss_indi”, and it was also written as “brfss_indi.csv” file, stored in the “data” folder.

d. Final resulting data files

A new variable named “date” which concatenated year, month, and day using was created in the “brfss_indi” dataframe. Then it was left-joined with “air_daily” using columns “county_code” and “date” (“brfss_indi” as the left table). The resulting dataset was saved as “brfss_with_air” data frame and was written as “brfss_with_air.csv” file in “data” folder.

In addition, another air quality dataset “air_daily2” was created by grouping and summarizing “air_daily”:

* mean_aqi_month: mean daily aqi value in that month
* max_aqi_month: max daily aqi value in that month
* min_aqi_month: min daily aqi value in that month
* mean_ozone_month: mean ozone value in that month (unit of measure: parts per million) 
* mean_pm2_5_month:  mean pm2.5 value in that month (unit of measure: Micrograms/cubic meter (LC))   
* mean_pm10_month: mean pm10 value in that month (unit of measure: Micrograms/cubic meter (25 C))  
* mean_co_month: mean carbon monoxide value in that month (unit of measure: parts per million)     
* mean_no2_month: mean nitrogen dioxide value in that month (unit of measure: parts per million)    
* mean_so2_month: mean sulfur dioxide value in that month (unit of measure: parts per million)

Then “brfss_indi” and “air_daily2” were left-joined using columns “county_code”, “year”, and “month” (“brfss_indi” as the left table). The resulting dataset was saved as “brfss_with_air2” data frame and was written as “brfss_with_air2.csv” file in the “data” folder.



## Exploratory Data Analysis


## Statistical Analysis


## Mapping and Spatial Analysis


## Next Steps and Discussion


## Findings and Summary


## Limitations and Reflections